apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- applications/cloudnative-pg-operator.yaml
- applications/cinelist-dev.yaml
- applications/cinelist-prod.yaml

commonLabels:
  managed-by: argocd
  project: cinelist