frontend:
  image:
    repository: ghcr.io/deivisondelmiro/cinelist-frontend
    tag: "20251124032606-098079ed"
backend:
  image:
    repository: ghcr.io/deivisondelmiro/cinelist-backend
    tag: "20251124032606-098079ed"
