frontend:
  image:
    repository: ghcr.io/deivisondelmiro/cinelist-frontend
    tag: "20251123043151-15ec6c97"
backend:
  image:
    repository: ghcr.io/deivisondelmiro/cinelist-backend
    tag: "20251123043151-15ec6c97"
