frontend:
  image:
    repository: ghcr.io/deivisondelmiro/cinelist-frontend
    tag: "20251202222119-354c0932"
backend:
  image:
    repository: ghcr.io/deivisondelmiro/cinelist-backend
    tag: "20251202222119-354c0932"
