frontend:
  image:
    repository: ghcr.io/deivisondelmiro/cinelist-frontend
    tag: "20251124054449-d53488d1"
backend:
  image:
    repository: ghcr.io/deivisondelmiro/cinelist-backend
    tag: "20251124054449-d53488d1"
