frontend:
  image:
    repository: ghcr.io/deivisondelmiro/cinelist-frontend
    tag: "20251124180752-d173897e"
backend:
  image:
    repository: ghcr.io/deivisondelmiro/cinelist-backend
    tag: "20251124180752-d173897e"
